import { TTasker } from '@/components/ui';

export const MOCK_TASKERS: TTasker[] = [
  {
    id: '1',
    name: 'Ali Raza',
    profileImage: '/images/profile.jpg',
    level: 'Expert',
    isOnsite: true,
    services: [
      'Air Conditioning & Ventilation',
      'Air Duct Cleaning',
      'Gas Refill',
      'Compressor Repair',
      'Copper Wiring',
      'Remote Repair',
    ],
    serviceImage: '/images/acRepair.png',
    location: 'Sabzazar Lahore',
    currency: 'PKR',
    price: 4500,
  },
  {
    id: '2',
    name: 'Waqas Aslam',
    profileImage: '/images/profile2.jpg',
    level: 'Beginner',
    isOnsite: true,
    services: [
      'Compressor Repair',
      'Air Conditioning & Ventilation',
      'Air Duct Cleaning',
      'Gas Refill',
    ],
    serviceImage: '/images/Painter.png',
    location: 'Sadarr Lahore',
    currency: 'PKR',
    price: 2500,
  },
  {
    id: '3',
    name: 'Asim',
    profileImage: '/images/profile3',
    level: 'Expert',
    isOnsite: true,
    services: [
      'Compressor Repair',
      'Air Duct Cleaning',
      'Copper Wiring',
      'Remote Repair',
    ],
    serviceImage: '/images/Photographer.png',
    location: 'Fe-4 Islamabad',
    currency: 'PKR',
    price: 1500,
  },
  {
    id: '4',
    name: 'Zunair Ali',
    profileImage: '/images/profile4.jpg',
    level: 'Mid Level',
    isOnsite: true,
    services: ['Compressor Repair', 'Copper Wiring', 'Remote Repair'],
    serviceImage: '/images/Sweeper.png',
    location: 'Faisalabad',
    currency: 'PKR',
    price: 5000,
  },
];
