import { TTasker } from '@/components/ui';

export const MOCK_TASKERS: TTasker[] = [
  {
    id: '1',
    name: 'Ali Raza',
    profileImage: '/images/profile.jpg',
    level: 'Expert',
    isOnsite: true,
    services: [
      {
        id: '1-Air Conditioning & Ventilation',
        name: 'Air Conditioning & Ventilation',
      },
      { id: '1-Air Duct Cleaning', name: 'Air Duct Cleaning' },
      { id: '1-Gas Refill', name: 'Gas Refill' },
      { id: '1-Compressor Repair', name: 'Compressor Repair' },
      { id: '1-Copper Wiring', name: 'Copper Wiring' },
      { id: '1-Remote Repair', name: 'Remote Repair' },
    ],
    serviceImage: '/images/acRepair.png',
    location: 'Sabzazar Lahore',
    currency: 'PKR',
    price: 4500,
  },
  {
    id: '2',
    name: 'Waqas Aslam',
    profileImage: '/images/profile2.jpg',
    level: 'Beginner',
    isOnsite: true,
    services: [
      { id: '2-Compressor Repair', name: 'Compressor Repair' },
      {
        id: '2-Air Conditioning & Ventilation',
        name: 'Air Conditioning & Ventilation',
      },
      { id: '2-Air Duct Cleaning', name: 'Air Duct Cleaning' },
      { id: '2-Gas Refill', name: 'Gas Refill' },
    ],
    serviceImage: '/images/Painter.png',
    location: 'Sadarr Lahore',
    currency: 'PKR',
    price: 2500,
  },
  {
    id: '3',
    name: 'Asim',
    profileImage: '/images/profile3.jpg',
    level: 'Expert',
    isOnsite: true,
    services: [
      { id: '3-Compressor Repair', name: 'Compressor Repair' },
      { id: '3-Air Duct Cleaning', name: 'Air Duct Cleaning' },
      { id: '3-Copper Wiring', name: 'Copper Wiring' },
      { id: '3-Remote Repair', name: 'Remote Repair' },
    ],
    serviceImage: '/images/Photographer.png',
    location: 'Fe-4 Islamabad',
    currency: 'PKR',
    price: 1500,
  },
  {
    id: '4',
    name: 'Zunair Ali',
    profileImage: '/images/profile4.jpg',
    level: 'Mid Level',
    isOnsite: true,
    services: [
      { id: '4-Compressor Repair', name: 'Compressor Repair' },
      { id: '4-Copper Wiring', name: 'Copper Wiring' },
      { id: '4-Remote Repair', name: 'Remote Repair' },
    ],
    serviceImage: '/images/Sweeper.png',
    location: 'Faisalabad',
    currency: 'PKR',
    price: 5000,
  },
];
